dist: xenial   # required for Python >= 3.7
language: python
python:
  - '3.7'
install:
  - pip install coveralls
script:
  - coverage run --branch --source=rosteron setup.py test
after_success:
  - coveralls
